version: 0.2

env:
  exported-variables:
    - CORE_STACK_NAME

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install aws-sam-cli
      - pip install -r lambda/tests/requirements.txt

  pre_build:
    commands:
      - pytest -s -vvv lambda/tests/
      - export CORE_STACK_NAME=${INSTALLATION_NAME}-core
      - export ECR_REPO_NAME=${CORE_STACK_NAME}/bclaw_runner
      - export ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f5)
      - aws ecr create-repository --repository-name $ECR_REPO_NAME || true
      - >
        export ECR_REPO_URI=$(aws ecr describe-repositories
        --repository-name $ECR_REPO_NAME
        --query "repositories[0].repositoryUri"
        --output text)

  build:
    commands:
      - cd bclaw_runner
      - docker build --target test -f Dockerfile.alpine .
      - docker build -t $ECR_REPO_URI -f Dockerfile.alpine .

      - cd $CODEBUILD_SRC_DIR
      - sam build -b ./build -s . -t cloudformation/bc_core.yaml
      - >
        sam package
        --template-file build/template.yaml
        --s3-bucket ${RESOURCE_BUCKET_NAME}
        --s3-prefix lambda
        --output-template-file build/packaged.yaml
      - >
        sam deploy
        --template-file build/packaged.yaml
        --stack-name ${CORE_STACK_NAME}
        --capabilities CAPABILITY_NAMED_IAM
        --s3-prefix lambda
        --no-fail-on-empty-changeset
        --parameter-overrides
        AmiId=${AMI_ID_SSM}
        CompilerMacroName=${COMPILER_MACRO_NAME}
        InstallationName=${INSTALLATION_NAME}
        LauncherBucketName=${LAUNCHER_BUCKET_NAME}
        LogRetentionDays=${LOG_RETENTION_DAYS}
        MaxvCpus=${MAX_VCPUS}
        MinvCpus=${MIN_VCPUS}
        ResourceBucketName=${RESOURCE_BUCKET_NAME}
        RootVolumeSize=${ROOT_VOLUME_SIZE}
        RunnerImageURI=${ECR_REPO_URI}
        ScratchVolumeSize=${SCRATCH_VOLUME_SIZE}
        SecurityGroups=${SECURITY_GROUPS}
        Subnets=${SUBNETS}
        Uniqifier=$(date | md5sum | head -c 16)
        VpcId=${VPC_ID}

  post_build:
    commands:
      - >
        aws ecr get-login-password --region ${AWS_REGION} |
        docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - docker push ${ECR_REPO_URI}

artifacts:
  discard-paths: yes
  files:
    - cloudformation/wf_launcher.yaml
    - cloudformation/wf_notifications.yaml
