AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RoleName:
    Type: String
    Default: "default"

  PolicyName:
    Type: String
    Default: "default"

Conditions:
  UseDefaultRoleName: !Or [ !Equals [!Ref RoleName, "Default"],
                            !Equals [!Ref RoleName, "default"] ]

  UseDefaultPolicyName: !Or [ !Equals [!Ref PolicyName, "Default"],
                              !Equals [!Ref PolicyName, "default"] ]

Resources:
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        !If [UseDefaultRoleName, !Ref AWS::NoValue, !Ref RoleName]
#        !If [UseDefaultRoleName, !Sub "${AWS::StackName}-${AWS::Region}", !Ref RoleName]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  EcsTaskPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        !If [UseDefaultPolicyName, !Ref AWS::NoValue, !Ref PolicyName]
#      ManagedPolicyName: !Sub "${EcsTaskRole}-policy"
      Roles:
        - !Ref EcsTaskRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
          - Effect: "Allow"
            Action:
              - "s3:ListBucket"
            Resource: "arn:aws:s3:::*"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:PutObjectAcl"
              - "s3:AbortMultipartUpload"
            Resource: "arn:aws:s3:::*/*"
          - Effect: "Allow"
            Action:
              - "s3:DeleteObject"
            Resource: "arn:aws:s3:::*/_control_/*"
          - Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
            Resource: "*"

Outputs:
  EcsTaskRoleArn:
    Value: !GetAtt EcsTaskRole.Arn

  EcsTaskPolicyArn:
    Value: !Ref EcsTaskPolicy
