AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  EcsTaskPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-${AWS::Region}-policy"
      Roles:
        - !Ref EcsTaskRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
          - Effect: "Allow"
            Action:
              - "s3:ListBucket"
            Resource: "arn:aws:s3:::*"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:PutObjectAcl"
              - "s3:AbortMultipartUpload"
            Resource: "arn:aws:s3:::*/*"
          - Effect: "Allow"
            Action:
              - "s3:DeleteObject"
            Resource: "arn:aws:s3:::*/_control_/*"
          - Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
            Resource: "*"
