AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  WorkflowName:
    Type: String

  StateMachineArn:
    Type: String

  LauncherBucketName:
    Type: String

  NamerLambdaArn:
    Type: String

# todo: notifications topic

Resources:
  wfDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      # https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/989
      SqsManagedSseEnabled: true
#      KmsMasterKeyId: "alias/aws/sqs"

  wfIncomingJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      SqsManagedSseEnabled: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt wfDeadLetterQueue.Arn
        maxReceiveCount: 3
#      KmsMasterKeyId: "alias/aws/sqs"

  wfIncomingJobsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !GetAtt wfIncomingJobsQueue.QueueName
      PolicyDocument:
        Version: "2012-10-17"
        Id: "wfIncomingJobsQueuePolicyDocument"
        Statement:
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: "SQS:SendMessage"
            Resource: !GetAtt wfIncomingJobsQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !GetAtt wfEventRule.Arn

  wfEventRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSQSFullAccess"

  wfNamerEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt wfIncomingJobsQueue.Arn
      FunctionName: !Ref NamerLambdaArn

  # todo: incoming queue DONE
  # todo: event source mapping DONE
  # todo: cloudwatch alarm

  # todo: target -> incoming queue DONE
  wfEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${WorkflowName}"
      EventBusName: default
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Ref LauncherBucketName
          object:
            key:
              -
                prefix: !Sub "${WorkflowName}/"
      State: ENABLED
      RoleArn: !GetAtt wfEventRuleRole.Arn
      Targets:
        -
          Id: todo
          Arn: !GetAtt wfIncomingJobsQueue.Arn
          DeadLetterConfig:
            Arn: !GetAtt wfDeadLetterQueue.Arn
          InputTransformer:
            InputPathsMap:
              bucket: "$.detail.bucket.name"
              key: "$.detail.object.key"
              version: "$.detail.object.version-id"
              replay: "$.replay-name"
            InputTemplate:
              !Sub >-
                {
                  "job_file": {
                    "bucket": <bucket>,
                    "key": <key>,
                    "version": <version>,
                    "s3_request_id": "DEPRECATED"
                  },
                  "replay": <replay>,
                  "index": "main",
                  "sfn_arn": "${StateMachineArn}"
                }
#        -
#          Arn: !Ref NamerLambdaArn
#          DeadLetterConfig:
#            Arn: !GetAtt wfDeadLetterQueue.Arn
#          Id: namer-lambda-target
#          InputTransformer:
#            InputPathsMap:
#              bucket: "$.detail.bucket.name"
#              key: "$.detail.object.key"
#              version: "$.detail.object.version-id"
#              replay: "$.replay-name"
#            InputTemplate:
#              !Sub >-
#                {
#                  "job_file": {
#                    "bucket": <bucket>,
#                    "key": <key>,
#                    "version": <version>,
#                    "s3_request_id": "DEPRECATED"
#                  },
#                  "replay": <replay>
#                  "index": "main",
#                  "sfn_arn": "${StateMachineArn}"
#                }

  wfEventArchive:
    Type: AWS::Events::Archive
    Properties:
      ArchiveName: !Sub "${WorkflowName}-events"
      SourceArn: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Ref LauncherBucketName
          object:
            key:
              -
                prefix: !Sub "${WorkflowName}/"

  wfDLQPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !GetAtt wfDeadLetterQueue.QueueName
      PolicyDocument:
        Version: 2012-10-17
        Id: wfDLQPolicyID
        Statement:
          -
            Sid: "wfEventRuleToDLQ"
            Effect: Allow
            Principal:
              AWS: "*"
            Action: "SQS:SendMessage"
            Resource:
              - !GetAtt wfDeadLetterQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !GetAtt wfEventRule.Arn
