AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  WorkflowName:
    Type: String

  HandlerLambdaArn:
    Type: String

  JobStatusLambdaArn:
    Type: String

  StateMachineArn:
    Type: String

Resources:
  wfOutputSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${WorkflowName}-notifications"

  wfOutputSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2008-10-17"
        Id: !Sub "${WorkflowName}-notifications-policy"
        Statement:
          -
            Sid: "OwnerAccessOnly"
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - "SNS:GetTopicAttributes"
              - "SNS:SetTopicAttributes"
              - "SNS:AddPermission"
              - "SNS:RemovePermission"
              - "SNS:DeleteTopic"
              - "SNS:Subscribe"
              - "SNS:ListSubscriptionsByTopic"
              - "SNS:Publish"
              - "SNS:Receive"
            Resource: !Ref wfOutputSNSTopic
            Condition:
              StringEquals:
                "AWS:SourceOwner": !Ref AWS::AccountId
          -
            Sid: "PublishThruSSLOnly"
            Action: "SNS:Publish"
            Effect: Deny
            Resource:
              - !Ref wfOutputSNSTopic
            Condition:
              Bool:
                "aws:SecureTransport": "false"
            Principal: "*"
      Topics:
        - !Ref wfOutputSNSTopic

  wfSFNtoLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.states
        detail-type:
          - Step Functions Execution Status Change
        detail:
          stateMachineArn:
            - !Ref StateMachineArn
      State: ENABLED
      Targets:
        -
          Arn: !Ref HandlerLambdaArn
          Id: HandlerLambdaTargetId
          InputTransformer:
            InputPathsMap:
              detail: "$.detail"
            InputTemplate:
              !Sub |-
                {
                  "workflow_name": "${WorkflowName}",
                  "sns_topic_arn": "${wfOutputSNSTopic}",
                  "event": <aws.events.event>,
                  "detail": <detail>
                }

  wfJobStatusSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref JobStatusLambdaArn
      Protocol: lambda
      TopicArn: !Ref wfOutputSNSTopic

Outputs:
  wfOutputTopicArn:
    Value: !Ref wfOutputSNSTopic
